import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


export default async function Home() {
  const  news = await fetchNews()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <h1>HN Feed</h1>
          <h2>We 🧡 hacker news!</h2>
        </div>
        <div>
          <ul>{news.map(item,i => (
            <li className={styles.list} key={i}> {item?.hits?.story_title}</li>
        ) )}
          </ul>
        </div>
      </main>
    </>
  )
}
